BUILD: Add make targets to build static executables and create disk image on OS X

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -96,8 +96,11 @@ _wxpath="$PATH"
 _prefix=/usr/local
 _wxincludes=""
 _wxlibs=""
+_wxstaticlibs=""
 _freetypeincludes=""
 _freetypelibs=""
+_staticlibpath=""
+_xcodetoolspath=""
 _amigaos4path="Games:ScummVM-Tools"
 
 # For cross compiling
@@ -447,6 +450,12 @@ for ac_option in $@; do
 		arg=`echo $ac_option | cut -d '=' -f 2`
 		BOOST_CFLAGS="-I$arg/include"
 		BOOST_LIBS="-L$arg/lib"
+		;;
+	--with-staticlib-prefix=*)
+		_staticlibpath=`echo $ac_option | cut -d '=' -f 2`
+		;;
+	--with-xcodetools-path=*)
+		_xcodetoolspath=`echo $ac_option | cut -d '=' -f 2`
 		;;
 	--enable-debug)
 		_debug_build=yes
@@ -1066,8 +1075,8 @@ case $_host_os in
 	darwin*)
 		DEFINES="$DEFINES -DMACOSX"
 		LIBS="$LIBS -framework AudioUnit -framework AudioToolbox -framework Carbon -framework CoreMIDI"
-		add_line_to_config_mk 'MACOSX = 1'
-
+		add_line_to_config_mk 'MACOSX = 1'	
+		
 		# Now we may have MacPorts or Fink installed
 		# Which put libraries and headers in non-standard places
 		# Checking them here
@@ -1088,6 +1097,78 @@ case $_host_os in
 
 			LDFLAGS="-L${macport_prefix}/lib $LDFLAGS"
 			CXXFLAGS="-I${macport_prefix}/include $CXXFLAGS"
+
+			if test -z "$_staticlibpath"; then
+				_staticlibpath=${macport_prefix}
+				echo "Set staticlib-prefix to ${_staticlibpath}"
+			fi
+		fi
+
+		# Fink
+		# There is no way to get the prefix, so implementing a hack here
+		fink_version=`fink -V 2>/dev/null`
+		if test "$?" -eq 0; then
+			fink_version="`echo "${fink_version}" | sed -ne 's/Package manager version: \([0-9.]*\)/\1/gp'`"
+			echo_n "You seem to be running Fink version ${fink_version}..."
+
+			fink_prefix=`which fink`
+			# strip off /bin/fink from /sw/bin/port
+			fink_prefix=`dirname ${fink_prefix}`
+			fink_prefix=`dirname ${fink_prefix}`
+
+			echo "adding ${fink_prefix} to paths"
+
+			LDFLAGS="-L${fink_prefix}/lib $LDFLAGS"
+			CXXFLAGS="-I${fink_prefix}/include $CXXFLAGS"
+
+			if test -z "$_staticlibpath"; then
+				_staticlibpath=${fink_prefix}
+				echo "Set staticlib-prefix to ${_staticlibpath}"
+			fi
+		fi
+
+		# Homebrew
+		brew_version=`brew -v 2>/dev/null`
+		if test "$?" -eq 0; then
+			brew_version="`echo "${brew_version}" | sed -ne 's/Homebrew \([0-9.]*\)/\1/gp'`"
+			echo_n "You seem to be running Homebrew version ${brew_version}..."
+
+			brew_prefix=`brew --prefix`
+
+			echo "adding ${brew_prefix} to paths"
+
+			LDFLAGS="-L${brew_prefix}/lib $LDFLAGS"
+			CXXFLAGS="-I${brew_prefix}/include $CXXFLAGS"
+
+			if test -z "$_staticlibpath"; then
+				_staticlibpath=${brew_prefix}
+				echo "Set staticlib-prefix to ${_staticlibpath}"
+			fi
+		fi
+
+		# If _staticlibpath is not set yet try first /sw (fink) then /usr/local
+		# (the macports case is handled above).
+		if test -z "$_staticlibpath"; then
+			if test -d "/sw"; then
+				_staticlibpath=/sw
+				echo "Set staticlib-prefix to ${_staticlibpath}"
+			elif test -d "/usr/local"; then
+				_staticlibpath=/usr/local
+				echo "Set staticlib-prefix to ${_staticlibpath}"
+			else
+				echo "Could not determine prefix for static libraries"
+			fi
+		fi
+		
+		# If _xcodetoolspath is not set yet use xcode-select to get the path
+		if test -z "$_xcodetoolspath"; then
+			_xcodetoolspath=`xcode-select -print-path`/Tools
+			if test -d "$_xcodetoolspath"; then
+				echo "Set xcodetools-path to ${_xcodetoolspath}"
+			else
+				_xcodetoolspath=
+				echo "Could not determine path for Xcode Tools"
+			fi
 		fi
 		;;
 	freebsd*)
@@ -1541,6 +1622,11 @@ fi
 if test "$_wxwidgets" = yes ; then
 	_wxincludes="`$_wxconfig --prefix="$_wxpath" --cflags`"
 	_wxlibs="`$_wxconfig --prefix="$_wxpath" --libs`"
+	_wxstaticlibs="`$_wxconfig --prefix="$_wxpath" --static --libs 2> /dev/null`"
+	_wxstaticlibs=`echo $_wxstaticlibs | sed 's|-lpng||' | sed 's|-lz||'`
+	# _wxstaticlibs may contain non-static libraries that we also have in _wxstaticlibs.
+	# remove those to avoid dependency on non-static libraries
+	
 	# Use the compiler specified by wx-config. This is needed on some systems to get a working executable.
 	CXX="`$_wxconfig --cxx`"
 	LD=$CXX
@@ -1574,6 +1660,7 @@ EOF
 	if test "$has_wx_gui_dev" = no ; then
 		_wxincludes=""
 		_wxlibs=""
+		_wxstaticlibs=""
 		_wxwidgets=no
 		echo "not found"
 	else
@@ -1648,6 +1735,8 @@ WINDRESFLAGS := $WINDRESFLAGS
 WIN32PATH=$_win32path
 AMIGAOS4PATH=$_amigaos4path
 STATICLIBPATH=$_staticlibpath
+XCODETOOLSPATH=$_xcodetoolspath
+
 
 EXEEXT := $HOSTEXEEXT
 
@@ -1666,6 +1755,7 @@ LDFLAGS += $LDFLAGS
 
 WXINCLUDES := $_wxincludes
 WXLIBS := $_wxlibs
+WXSTATICLIBS := $_wxstaticlibs
 
 FREETYPEINCLUDES := $_freetypeincludes
 FREETYPELIBS := $_freetypelibs
